name: Deploy GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Copy site files to _site (excluding _site itself)
        run: |
          mkdir -p _site
          bash -O extglob -c 'cp -r !(._site|_site|.git|.github) _site/'
        shell: bash

      - name: Disable Jekyll
        run: touch _site/.nojekyll

      - name: List contents of _site
        run: ls -R _site

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4