name: Deploy GitHub Pages with Submodules

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Copy site files to _site (including submodules)
        run: |
          mkdir -p _site/news
          shopt -s extglob
          cp -r !(._site|.git|.github) _site/
          cp -r news/news_2024 _site/news/
        shell: bash

      - name: Disable Jekyll
        run: touch _site/.nojekyll

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4